version: 2
updates:
  - package-ecosystem: "github-actions"
    commit-message:
      prefix: "build(deps): "
    directory: "/"
    schedule:
      interval: "monthly"
      day: monday
      time: "04:00"
    open-pull-requests-limit: 99
  - package-ecosystem: "pip"
    commit-message:
      prefix: "build(deps): "
    directory: "/"
    schedule:
      interval: "monthly"
      day: monday
      time: "04:00"
    open-pull-requests-limit: 99
  - package-ecosystem: "devcontainers"
    commit-message:
      prefix: "build(deps): "
    directory: "/"
    schedule:
      interval: "monthly"
      day: monday
      time: "04:00"
    open-pull-requests-limit: 99
  - package-ecosystem: "bun"
    commit-message:
      prefix: "build(deps): "
    directory: "web/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 99
